services:
  marzban:
    image: gozargah/marzban:latest
    restart: always
    env_file: .env
    ports:
      - "8001:8001"
    #network_mode: host
    volumes:
      - /var/lib/marzban:/var/lib/marzban
